apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  title: office-js-helpers
  description: >
    This library is a fork of an open-source repo of
    helpers for Office Add-ins. I think our
    [Excel Integration App](https://github.com/appfolio/excel_integration_app/)
    uses it to authenticate to APM.
  tags: []
  annotations:
    appfolio.com/package-location: url:https://github.com/appfolio/office-js-helpers/pkgs/npm/office-js-helpers
    appfolio.com/package-type: npm
  name: office-js-helpers
spec:
  type: library
  lifecycle: maintenance
  owner: weird-algorithm
